// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsVSyOqrMduUlgE12TW-dKIAYDxSMr8s0',
    appId: '1:115436920855:web:2b0dc0de4e153287683c52',
    messagingSenderId: '115436920855',
    projectId: 'chrain-2cfd9',
    authDomain: 'chrain-2cfd9.firebaseapp.com',
    storageBucket: 'chrain-2cfd9.appspot.com',
    measurementId: 'G-GJZHMJE01X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGvKgHR4qHuTe_oekim3rLUC0T32Mse0M',
    appId: '1:115436920855:android:5af35a6f9b5f07a6683c52',
    messagingSenderId: '115436920855',
    projectId: 'chrain-2cfd9',
    storageBucket: 'chrain-2cfd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqlHm7MoOrmI1udM6Gg9lbXxgT3IFkIiA',
    appId: '1:115436920855:ios:630365e962f9d292683c52',
    messagingSenderId: '115436920855',
    projectId: 'chrain-2cfd9',
    storageBucket: 'chrain-2cfd9.appspot.com',
    androidClientId: '115436920855-l061q8a7hmu2ovg6gffds2l7m6nr0ccg.apps.googleusercontent.com',
    iosBundleId: 'com.example.spAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqlHm7MoOrmI1udM6Gg9lbXxgT3IFkIiA',
    appId: '1:115436920855:ios:cf70fe1f5499725a683c52',
    messagingSenderId: '115436920855',
    projectId: 'chrain-2cfd9',
    storageBucket: 'chrain-2cfd9.appspot.com',
    androidClientId: '115436920855-l061q8a7hmu2ovg6gffds2l7m6nr0ccg.apps.googleusercontent.com',
    iosBundleId: 'com.example.spAi.RunnerTests',
  );
}
